$( function() {
    var elemento = [
        "Hidrogênio",
        "Hélio",
        "Lítio",
        "Berílio",
        "Boro",
        "Carbono",
        "Nitrogênio",
        "Oxigênio",
        "Flúor",
        "Neônio",
        "Sódio",
        "Magnésio",
        "Alumínio",
        "Silício",
        "Fósforo",
        "Enxofre",
        "Cloro",
        "Argônio",
        "Potássio",
        "Cálcio",
        "Escândio",
        "Titânio",
        "Vanádio",
        "Cromo",
        "Manganês",
        "Ferro",
        "Cobalto",
        "Níquel",
        "Cobre",
        "Zinco",
        "Gálio",
        "Germânio",
        "Arsênio",
        "Selênio",
        "Bromo",
        "Criptônio",
        "Rubídio",
        "Estrôncio",
        "Ítrio",
        "Zircônio",
        "Nióbio",
        "Molibdênio",
        "Tecnécio",
        "Rutênio",
        "Ródio",
        "Paládio",
        "Prata",
        "Cádmio",
        "Índio",
        "Estanho",
        "Antimônio",
        "Telúrio",
        "Iodo",
        "Xenônio",
        "Césio",
        "Bário",
        "Lantânio",
        "Cério",
        "Praseodímio",
        "Neodímio",
        "Promécio",
        "Samário",
        "Európio",
        "Gadolínio",
        "Térbio",
        "Disprósio",
        "Hólmio",
        "Érbio",
        "Túlio",
        "Itérbio",
        "Lutécio",
        "Háfnio",
        "Tântalo",
        "Tungstênio",
        "Rênio",
        "Ósmio",
        "Iridio",
        "Platina",
        "Ouro",
        "Mercúrio",
        "Tálio",
        "Chumbo",
        "Bismuto",
        "Polônio",
        "Astato",
        "Radônio",
        "Frâncio",
        "Rádio",
        "Actínio",
        "Tório",
        "Protactínio",
        "Urânio",
        "Netúnio",
        "Plutônio",
        "Amerício",
        "Cúrio",
        "Berquélio",
        "Califórnio",
        "Einstêinio",
        "Férmio",
        "Mendelévio",
        "Nobélio",
        "Laurêncio",
        "Rutherfórdio",
        "Dúbnio",
        "Seabórgio",
        "Bóhrio",
        "Hássio",
        "Meitnério",
        "Darmstácio",
        "Roentgênio",
        "Copernício",
        "Niônio",
        "Fleróvio",
        "Moscóvio",
        "Livermório",
        "Tenessínio",
        "Oganessônio"
    ];
    $( "#elemento" ).autocomplete({
    source: elemento
    });
} );


function validar(valida_registro) {
        
    var senha = valida_registro.senha.value;
    var confirmaSenha = valida_registro.confirmaSenha.value;


    if (senha != confirmaSenha) {
        alert('Senhas diferentes.');
        valida_registro.senha.focus();
        return false;
    } if (senha.length < 6) {
        alert('Senha precisa ter no mínimo 6 caracteres.');
        valida_registro.senha.focus();
        return false;
    }
}